apiVersion: v1
kind: Service
metadata:
  name: {{.JobName}}-svc-{{ .Replica }}
spec:
  selector:
    app: {{.JobName}}-app-{{.Replica}}
  ports:
  - name: serviceport
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
