---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: true
    esServers: [https://elastic-tls-elk.apps.rsevilla-ocp45-ovn.perf-testing.devcluster.openshift.com]
    insecureSkipVerify: true
    defaultIndex: kubelet-density
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kubelet-density-podlatency

jobs:
  - name: kubelet-density
    jobIterations: 10000
    qps: 10
    burst: 10
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: gcr.io/google_containers/pause-amd64:3.0
