---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: true
    esServers: [https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com]
    insecureSkipVerify: false
    defaultIndex: kubelet-density
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kubelet-density-podlatency

jobs:
  - name: kubelet-density
    jobIterations: 1000  
    qps: 10
    burst: 10
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: gcr.io/google_containers/pause-amd64:3.0
