---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: true
    esServers: [https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner

jobs:
  - name: api-intensive
    jobIterations: 700
    qps: 4
    burst: 4
    namespacedIterations: true
    namespace: api-intensive
    podWait: false
    cleanup: true
    waitFor: []
    waitWhenFinished: true
    objects:
      - objectTemplate: assets/deployment.yaml
        replicas: 1
      - objectTemplate: assets/configmap.yaml
        replicas: 1
      - objectTemplate: assets/secret.yaml
        replicas: 1
      - objectTemplate: assets/service.yaml
        replicas: 1

  - name: api-intensive-remove
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Deployment
        labelSelector: {kube-burner-job: api-intensive}
        apiVersion: apps/v1

  - name: ensure-pods-removal
    qps: 10
    burst: 10
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Pod
        labelSelector: {kube-burner-job: api-intensive}

  - name: remove-services
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Service
        labelSelector: {kube-burner-job: api-intensive}

  - name: remove-configmaps-secrets
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: ConfigMap
        labelSelector: {kube-burner-job: api-intensive}
      - kind: Secret
        labelSelector: {kube-burner-job: api-intensive}

